/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import Clases.Conexion;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import Clases.Proveedor;
import java.sql.PreparedStatement;
import java.sql.Connection;


        


/**
 *
 * @author braya
 */
public class Proveedores extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public Proveedores() {
        initComponents();
        mostrarProveedor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonreportediario = new javax.swing.JButton();
        botonsalir = new javax.swing.JButton();
        botoncategorias = new javax.swing.JButton();
        botonproveedores = new javax.swing.JButton();
        botonhistorialdemovimientos = new javax.swing.JButton();
        botonusuario = new javax.swing.JButton();
        botonproducto = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Proveedore = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(42, 138, 127));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Proveedores");

        jPanel2.setBackground(new java.awt.Color(25, 39, 52));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        botonreportediario.setBackground(new java.awt.Color(25, 39, 52));
        botonreportediario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonreportediario.setForeground(new java.awt.Color(255, 255, 255));
        botonreportediario.setText("Reporte Diario");
        botonreportediario.setBorderPainted(false);
        botonreportediario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonreportediarioActionPerformed(evt);
            }
        });

        botonsalir.setBackground(new java.awt.Color(25, 39, 52));
        botonsalir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonsalir.setForeground(new java.awt.Color(255, 255, 255));
        botonsalir.setText("Salir");
        botonsalir.setBorderPainted(false);
        botonsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsalirActionPerformed(evt);
            }
        });

        botoncategorias.setBackground(new java.awt.Color(25, 39, 52));
        botoncategorias.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botoncategorias.setForeground(new java.awt.Color(255, 255, 255));
        botoncategorias.setText("Categorias");
        botoncategorias.setBorderPainted(false);
        botoncategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncategoriasActionPerformed(evt);
            }
        });

        botonproveedores.setBackground(new java.awt.Color(25, 39, 52));
        botonproveedores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonproveedores.setForeground(new java.awt.Color(255, 255, 255));
        botonproveedores.setText("Proveedores");
        botonproveedores.setBorderPainted(false);
        botonproveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonproveedoresActionPerformed(evt);
            }
        });

        botonhistorialdemovimientos.setBackground(new java.awt.Color(25, 39, 52));
        botonhistorialdemovimientos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonhistorialdemovimientos.setForeground(new java.awt.Color(255, 255, 255));
        botonhistorialdemovimientos.setText("Movimientos");
        botonhistorialdemovimientos.setBorderPainted(false);
        botonhistorialdemovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonhistorialdemovimientosActionPerformed(evt);
            }
        });

        botonusuario.setBackground(new java.awt.Color(25, 39, 52));
        botonusuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonusuario.setForeground(new java.awt.Color(255, 255, 255));
        botonusuario.setText("Usuario");
        botonusuario.setBorderPainted(false);
        botonusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonusuarioActionPerformed(evt);
            }
        });

        botonproducto.setBackground(new java.awt.Color(25, 39, 52));
        botonproducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonproducto.setForeground(new java.awt.Color(255, 255, 255));
        botonproducto.setText("Producto");
        botonproducto.setBorderPainted(false);
        botonproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonproductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(botonproducto)
                .addGap(30, 30, 30)
                .addComponent(botonusuario)
                .addGap(30, 30, 30)
                .addComponent(botonhistorialdemovimientos)
                .addGap(18, 18, 18)
                .addComponent(botonproveedores)
                .addGap(26, 26, 26)
                .addComponent(botoncategorias)
                .addGap(28, 28, 28)
                .addComponent(botonreportediario)
                .addGap(48, 48, 48)
                .addComponent(botonsalir)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonproducto)
                    .addComponent(botonusuario)
                    .addComponent(botonhistorialdemovimientos)
                    .addComponent(botonreportediario)
                    .addComponent(botonproveedores)
                    .addComponent(botoncategorias)
                    .addComponent(botonsalir))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(188, 188, 188));
        jTextField2.setText("Buscar proveedor");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(25, 39, 52));
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("Buscar");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField6.setBackground(new java.awt.Color(42, 138, 127));
        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("Nuevo Proveedor");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        Tabla_Proveedore.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono"
            }
        ));
        jScrollPane1.setViewportView(Tabla_Proveedore);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
public void mostrarProveedor(){
     DefaultTableModel modelo = new DefaultTableModel();
     modelo.addColumn("ID_Proveedor");
     modelo.addColumn("Nombre");
     modelo.addColumn("Telefono");
   
       try{Conexion conexion = new Conexion();
       Connection conn = conexion.conn;
       String sql = "SELECT * FROM Proveedor";
     PreparedStatement ps = conn.prepareStatement(sql);
       ResultSet datos = ps.executeQuery();
       
     while (datos.next()){
       int id = datos.getInt("id_proveedor");
       String nombre = datos.getString("nombre_proveedor");
       String telefono = datos.getString("telefono");
       String estatus = datos.getString("estatus");

       modelo.addRow(new Object[]{id,nombre,telefono});
       
           
       Tabla_Proveedore.setModel(modelo);
       }
 }catch(Exception e){
             JOptionPane.showMessageDialog(null,"Error:"
                     +e.getMessage());      
 }
    }
    
    

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void botonreportediarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonreportediarioActionPerformed
        ReporteDiario rep = new ReporteDiario();
        rep.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonreportediarioActionPerformed

    private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
        Inicio_de_sesion inicios = new Inicio_de_sesion();
        inicios.setVisible(true);
        dispose();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_botonsalirActionPerformed

    private void botoncategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncategoriasActionPerformed
        //este codigo es para que los botones funcionen
        GestionCategoria gestionc = new GestionCategoria();
        //Indicamos que se hace visible
        gestionc.setVisible(true);
        //cerramos esta ventana
        dispose();
        //Fin del codigo para abrir nuevas ventanas
        // TODO add your handling code here:
    }//GEN-LAST:event_botoncategoriasActionPerformed

    private void botonproveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonproveedoresActionPerformed
         Proveedores pro = new Proveedores();
        pro.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_botonproveedoresActionPerformed

    private void botonhistorialdemovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonhistorialdemovimientosActionPerformed
        HistorialDeMovimientos hmovimientos = new HistorialDeMovimientos();
        hmovimientos.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_botonhistorialdemovimientosActionPerformed

    private void botonusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonusuarioActionPerformed
GestionDeUsuario gesusuario = new GestionDeUsuario();
    gesusuario.setVisible(true);
    dispose();       }//GEN-LAST:event_botonusuarioActionPerformed

    private void botonproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonproductoActionPerformed
         //este codigo es para que los botones funcionen
        GestionProductos gestionp = new GestionProductos();
        //Indicamos que se hace visible
        gestionp.setVisible(true);
        //cerramos esta ventana
        dispose();
        //Fin del codigo para abrir nuevas ventanas


        // TODO add your handling code here:
    }//GEN-LAST:event_botonproductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proveedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proveedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_Proveedore;
    private javax.swing.JButton botoncategorias;
    private javax.swing.JButton botonhistorialdemovimientos;
    private javax.swing.JButton botonproducto;
    private javax.swing.JButton botonproveedores;
    private javax.swing.JButton botonreportediario;
    private javax.swing.JButton botonsalir;
    private javax.swing.JButton botonusuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
